version: 1.2.{build}
image: Visual Studio 2019
before_build:
- pwsh: nuget restore src/Rhyous.StringLibrary.sln
build:
  project: src/Rhyous.StringLibrary.sln
  verbosity: minimal
test:
  categories:
    except:
    - slow
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: YuESu/nQz4WK2RIjra4BXLJ7dDNM/7mJcKJAJQZCiYlKgMBPozzyCSRIBgu/72mC