version: 1.2.{build}
image: Visual Studio 2019
before_build:
- pwsh: nuget restore src/Rhyous.StringLibrary.sln
build:
  project: src/Rhyous.StringLibrary.sln
  verbosity: minimal
test:
  categories:
    except:
    - slow
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: /ivvRqgg2qJClJYIJcrQyBaKbKpYIElKRkjzxoGrfWvDNtnCg6FWjamd8CgPx07ec4SBCGdkZ5p0LQw81PPGIC0tcBp1pwg1Vk8FnF3gspVapYc/F0sjCdSf/b9yzIZhCJhQ4WyyNXGC4ZwKZrhC4Q==